#include <stdio.h>
#include <stdlib.h>
//#include <tchar.h>
#include <math.h>
#include <string.h>
#include <stdint.h>
#include "c_include/hypercv_core.h"
#include "c_include/hypercv_process.h"
#include "highgui/hypercv_gui.h"
#include "algorithm/hypercv_algorithm.h"
