#include <stdio.h>
#include <stdlib.h>
//#include <tchar.h>
#include <math.h>
#include <string.h>
#include <stdint.h>
#include "core/core.h"
#include "process/process.h"
#include "highgui/hypercv_gui.h"
#include "algorithm/Algorithm.h"
